### PR TITLE
Logging expansion

### PR DESCRIPTION
**Pull request by iPromKnight**
- Adds Promtail and Loki to the metrics stack, configuring them as a datasource in grafana on deployment 
- Adds a dashboard to monitor the system (logs for producer and consumer)
- Restructures the base directory so deployment manifests are moved into a deployments folder 
- Adds selective labels to producer, consumer and addon so that their logs are ingested by promtail

Dashboard added which will be auto deployed:

image

Covers #53 without the need to introduce new transports

### CODE REVIEW

**Comment by purple-emily** [comment]
Why move the docker-compose file? Isn't that our entry point so doesn't it make sense to keep it in the root folder?

**Comment by iPromKnight** [comment]
Just a way to better organise things
We're going to have a helm chart too soon - so deployment seemed like a better fit as k8s can live along side docker in there without making the root repo folder too "busy"

I've just updated the context paths in the compose - forgot to do that

**Comment by purple-emily** [comment]
I'm on my phone, but other than the moving the docker-compose file, I don't see any issues. I can't see the new folder structure easily so I can't see how easy it is to navigate 😅

**Comment by purple-emily** [comment]
I don't have the ability to test it until tomorrow

**Review by Gabisonfire — APPROVED** [review]
Looks good to me!

**Pull request merged**
