### PR TITLE
Monitoring with Grafana and Prometheus

### PR DESCRIPTION
**Pull request by HDwayne**
This pull request introduces a new docker-compose-metrics.yml file, which includes services for Prometheus and Grafana. The primary goal is to add RabbitMQ monitoring and visualization capabilities directly through Grafana

Changes Made:

- Introduced the docker-compose-metrics.yml file, incorporating Prometheus and Grafana services.
- Updated the README to provide instructions on configuring Prometheus and Grafana to monitor RabbitMQ.
- Included datasource.yml and prometheus.yml configuration files to seamlessly integrate Grafana and Prometheus.

### CODE REVIEW

**Comment by funkypenguin** [comment]
Ooh, I'm so keen on this! I've been thinking about how to setup a public grafana dashboard to geek out over the usage stats on https://torrentio.elfhosted.com - the more metrics, the better!

**Comment by prom3theu5** [comment]
Aye me too tbh 😄

**Comment by iPromKnight** [comment]
Aye Me too tbh 😄

**Comment by Gabisonfire** [comment]
Thank you, this is an excellent idea. I think we could even push this to get some metrics from the database. Was talking about this just yesterday to have an endpoint on the api but prometheus makes more sense.

**Comment by Gabisonfire** [comment]
Great PR, thank you.

**Comment by HDwayne** [comment]
I've integrated the PostgreSQL Exporter service to enable the collection of PostgreSQL metrics within Grafana. It would be nice to modify the `DATA_SOURCE_NAME` variable in the `docker-config-metrics` to ensure that database credentials aren't hardcoded but are instead dependent on environment variables. To be honest, I'm not entirely sure how to implement this change myself.

Additionally, I'd like to highlight that having access to torrents information would be an amazing addition ! As a quick update, I've added a `/statistics` endpoint to the addon for debugging purposes. Please remember to disable this endpoint for production purposes.

thank you !

**Pull request merged**
