### PR TITLE
QOL Fixes.

### PR DESCRIPTION
**Pull request by iPromKnight**
- Move compose to top level
- Comment out broken scrapers
- Remove db init scripts and use ENABLE_SYNC env var which the code base uses to specify if Sequelize should create or alter tables on startup, meaning we dont need manual db initialization. There were missing tables anyhow :P

### CODE REVIEW

**Comment by Gabisonfire** [comment]
Thanks a lot!

**Comment by dreulavelle** [comment]
I do get this issue though with the db.. and then it eventually crashes. 🤔 

image

**Comment by Gabisonfire** [comment]
@dreulavelle Are you running this on a Pi by any chance?

**Comment by dreulavelle** [comment]
Nah, arm vps though. Bumped db version to 7.0.5 as well without any luck

**Comment by Gabisonfire** [comment]
Yeah thats probably why, you'll need to find an image that supports arm

**Comment by dreulavelle** [comment]
`mysql/mysql-server:8.0.23` supports arm, but was getting connection issues

**Comment by dreulavelle** [comment]
`arm64v8/mysql:8.0.36-oracle` ah looks like they have a separate one for arm

**Pull request merged**
